//--------------------------------------------------------------------------------
// Auto-generated by LiteX (9ad3ecf74) on 2026-09-16 08:16:18
//--------------------------------------------------------------------------------
#ifndef __GENERATED_GIT_H
#define __GENERATED_GIT_H

#define LITEX_GIT_SHA1 "9ad3ecf74"
#endif
